-- 热门选题表
CREATE TABLE IF NOT EXISTS hot_topic (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'id',
    topicText VARCHAR(500) NOT NULL COMMENT '选题文本',
    emoji VARCHAR(20) NOT NULL DEFAULT '🔥' COMMENT '选题图标',
    year SMALLINT NOT NULL COMMENT '目标年份',
    month TINYINT NOT NULL COMMENT '目标月份',
    source VARCHAR(50) NOT NULL DEFAULT 'AI' COMMENT '来源：AI/MANUAL/DATA',
    sortOrder INT NOT NULL DEFAULT 0 COMMENT '排序（升序）',
    isActive TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    isDelete TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    INDEX idx_year_month (year, month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='热门选题表';
